spring.application.name=bloodbi-analytics-backend
server.port=8081

# Base MySQL XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/bloodbi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# Important: ne pas recréer les tables à chaque démarrage
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Important: désactiver l'initialisation automatique si tu as déjà importé data.sql dans phpMyAdmin
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Frontend/mobile development origins
bloodbi.cors.allowed-origins=http://localhost:3000,http://localhost:19006,http://127.0.0.1:3000